### ISSUE TITLE
android.proj broken

### ISSUE THREAD

**Issue by echorebel** [projmary/stachenblochen#1]
android.proj is broken. `Cocos2dxETCLoader cannot be resolved` and some more issues.
Will try to recreate the android folder. If that doesn't help maybe reset. cocos 3.4 is out.
How is the visual studio frontline?

**Comment by echorebel** [comment]
tried to build it via `cocos run -p android -j 4` but NDK build failed with `no rule to make target CCGLViewProtocol.cpp`.
I tested clean setup NDK build works there also Android project is fine at least. 
So reset to cocos 3.4 from scratch?

**Comment by eVillain** [comment]
I dunno what happened to the old one ¯\_(ツ)_/¯
It's been reset to 3.4

**Comment by echorebel** [comment]
runs again, had to re-add fix for https://github.com/cocos2d/cocos2d-x/pull/7526. shouldn't that be in a release already?

**Comment by echorebel** [comment]
additional info on the issue: http://www.cocos2d-x.org/news/307
